version: "3.1"

services:
  db:
    container_name: ${DB_HOST}
    image: postgres:13.2-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  webserver-activity:
    image: altimofeev/nginx-simple
    working_dir: ${ACTIVITY_WORKDIR}
    ports:
      - ${ACTIVITY_PORT}:80
    depends_on:
      - activity
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/activity.conf:/etc/nginx/conf.d/default.conf
      - ./activity:${ACTIVITY_WORKDIR}
      - sock_activity:${SOCKET_DIR}

  webserver-landing:
    image: altimofeev/nginx-simple
    working_dir: ${LANDING_WORKDIR}
    ports:
      - ${LANDING_PORT}:80
    depends_on:
      - landing
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/landing.conf:/etc/nginx/conf.d/default.conf
      - ./activity:${LANDING_WORKDIR}
      - sock_landing:${SOCKET_DIR}

  activity:
    image: altimofeev/php8.0-fpm
    container_name: activity
    working_dir: ${ACTIVITY_WORKDIR}
    depends_on:
      - db
    volumes:
      - ./activity:/data/activity
      - sock_activity:${SOCKET_DIR}

  landing:
    image: altimofeev/php8.0-fpm
    container_name: landing
    working_dir: ${LANDING_WORKDIR}
    depends_on:
      - activity
      - db
      - rabbitmq
    volumes:
      - ./landing:/data/landing
      - sock_landing:${SOCKET_DIR}

#  redis:
#    image: redis
#    container_name: ${REDIS_HOST}
#    working_dir: /data
#    volumes:
#      - ./redis-data:/data

  rabbitmq:
    image: rabbitmq:management
    container_name: ${RABBITMQ_HOST}
    hostname: ${RABBITMQ_HOST}
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST}
    ports:
      - ${RABBITMQ_PORT}:${RABBITMQ_PORT}
      - ${RABBITMQ_MANAGEMENT_PORT}:${RABBITMQ_MANAGEMENT_PORT}
    volumes:
      - ./rabbit/data:/var/lib/rabbitmq/
      - ./rabbit/log:/var/log/rabbitmq

volumes:
  sock_activity:
  sock_landing:
